name: DID-io Driver
on:
  push:
    paths:
    - 'drivers/did-io'
# TODO: Reenable for local validator
#  pull_request:
jobs:
  driver-build:
    name: Build, lint, and test the did-io driver on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x']
        os: [ubuntu-latest]

    defaults:
      run:
        working-directory: ./drivers/did-io

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Test
        run: yarn test --ci --coverage --maxWorkers=2

      - name: Build
        run: yarn build
